title: Vinay Thakur
description: Things to Express
url: "https://vtmade.github.io"
baseurl: ""

# Swiss theme
remote_theme: broccolini/swiss
theme_color: black

markdown: kramdown
permalink: /:title/
